# Generated by Django 4.2.1 on 2023-05-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Enter store brand', max_length=200),
        ),
    ]
